#:schema node_modules/wrangler/config-schema.json
name = "vod-gateway"
main = "src/index.ts"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "vod.dev-nyantube.aplulu.me"
custom_domain = true

[[r2_buckets]]
binding = "VOD_BUCKET"
bucket_name = "dev-nyantube-vod"

[vars]
CLOUDFRONT_KEY_PAIR_ID = "nyan"
CLOUDFRONT_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwArUbLL6+fXpx16Ba67f\n91KP2uvRrTUfsAaqwicpNO7ncH0wEAX2eOvl3c3yf7CBirVEq8jbP4ypsagZLuhr\nKwxOfxPxwxRa/asdvlCAcRLwPCZwnkbwDuoD8EKA00kdSsou8bJiaaK8W8XWoSK0\neWQld1PIwXb3pJdd1LObamRKO9NT1krJAevmqss+N6YfIwW1n2iUvX5GXCz1x83y\ncJryHdqlTu+V1d9iqHl+Q+fc+hnd7VgqpDTBJInSNwnPwDog5c4o+DdShEDqhupe\nQHJcPQYoS/R+3vekpcJTKcZXIMszugKy4B6LbEXST0cNVdGNMp9HI3RqGXH2UEsQ\nVQIDAQAB\n-----END PUBLIC KEY-----\n"
CACHE_TTL= "86400"

