// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file nyantube/vod/v1/vod.proto (package nyantube.vod.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetVideoRequest, GetVideoResponse } from './vod_pb';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * @generated from service nyantube.vod.v1.VODService
 */
export const VODService = {
  typeName: 'nyantube.vod.v1.VODService',
  methods: {
    /**
     * @generated from rpc nyantube.vod.v1.VODService.GetVideo
     */
    getVideo: {
      name: 'GetVideo',
      I: GetVideoRequest,
      O: GetVideoResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
